version: '2'
services:
  db:
    env_file:
      - /mnt/f/db.env
    image: mysql:5.7.25
    volumes:
      - ../mydata:/var/lib/mysql
    ports:
      - "3306:3306"
  api:
    privileged: true
    env_file:
      - /mnt/f/db.env
    build: .
    command: bundle exec rails s -p 2000 -b '0.0.0.0'
    volumes:
      - .:/myapp
      - /mnt/f/TV:/synivideo
      - /mnt/f/omedia:/omedia
    ports:
      - "2000:2000"
    depends_on:
      - db
  web:
    build: 
      context: .
      dockerfile: mynginx.Dockerfile
    volumes:
      - /mnt/f/TV:/usr/share/nginx/html/synivideo
      - /mnt/f/omedia:/usr/share/nginx/html/omedia
    ports:
      - "82:80"

